### ISSUE TITLE
Little sorting issue

### ISSUE THREAD

**Issue by Lythox-Supreme** [awesome-llama/resources#1]
So I really wanted to say how I love The Mast Pen+, it's just amazing.
I found a little sorting issue with the mast, when the player see it for the first time.

![image](https://github.com/awesome-llama/resources/assets/139252857/0c893f23-8896-4f2e-8de6-d2970e2015e6)

Keep up the good work awesome-llama 👍

**Comment by awesome-llama** [comment]
This file is not meant to be kept up to date, it was a one-off attempt responding to a Scratcher. I currently only maintain the scratch version of the project.
